### ISSUE TITLE
Bug on all captainfact.io/help/... pages

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#150]
Here: https://captainfact.io/help/privacy
![image](https://user-images.githubusercontent.com/15331478/97089323-37cb1300-1637-11eb-95f0-a8e28956d43e.png)
```TypeError: {(intermediate value)}.cwd is not a function
    at new c (https://captainfact.io/vendor.9cbb99e66d8e4e9b23d1.js:2:1408848)
    at c (https://captainfact.io/vendor.9cbb99e66d8e4e9b23d1.js:2:1408771)
    at Function.E.parse (https://captainfact.io/vendor.9cbb99e66d8e4e9b23d1.js:2:1403407)
    at g (https://captainfact.io/vendor.9cbb99e66d8e4e9b23d1.js:2:1005790)
    at ha (https://captainfact.io/vendor.9cbb99e66d8e4e9b23d1.js:2:1166623)
    at Au (https://captainfact.io/vendor.9cbb99e66d8e4e9b23d1.js:2:1211888)
    at Ts (https://captainfact.io/vendor.9cbb99e66d8e4e9b23d1.js:2:1197433)
    at js (https://captainfact.io/vendor.9cbb99e66d8e4e9b23d1.js:2:1197358)
    at Es (https://captainfact.io/vendor.9cbb99e66d8e4e9b23d1.js:2:1194698)
    at https://captainfact.io/vendor.9cbb99e66d8e4e9b23d1.js:2:1153028```

**Comment by Miragide** [comment]
Oops @Betree @francoispeyret ?
Any ideas?
https://github.com/CaptainFact/captain-fact-frontend/pull/685#event-3914568962

**Comment by Betree** [comment]
Introduced in dependency update: https://github.com/CaptainFact/captain-fact-frontend/pull/695

Reverting that now
