### ISSUE TITLE
Unexpected error when creating a comment with an URL which has a redirection

### ISSUE THREAD

**Issue by ghostwan** [CaptainFact/captain-fact#155]
# Describe the bug
*A clear description of what the bug is.*

I tried to create a comment with this URL  : "https://t.co/TNtZn7hmUa?amp=1" 

It seems that what could cause the issue is this URL has a redirection to this url "https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)30566-3/fulltext"

When I used the final URL it is redirected to, it finaly works. 

# Device
- OS: MacIntel
- Browser: `5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36`

# Context

**URL**: https://captainfact.io/videos/4Y7d

**Stacktrace**:
```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Burl%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Fi (https://captainfact.io/vendor.1162576fecf1045ff8b8.js:2:1162519)
    at https://captainfact.io/vendor.1162576fecf1045ff8b8.js:2:1167313
    at Qa (https://captainfact.io/vendor.1162576fecf1045ff8b8.js:2:1176140)
    at Tu (https://captainfact.io/vendor.1162576fecf1045ff8b8.js:2:1216095)
    at As (https://captainfact.io/vendor.1162576fecf1045ff8b8.js:2:1199699)
    at js (https://captainfact.io/vendor.1162576fecf1045ff8b8.js:2:1199624)
    at Es (https://captainfact.io/vendor.1162576fecf1045ff8b8.js:2:1196964)
    at https://captainfact.io/vendor.1162576fecf1045ff8b8.js:2:1155294
    at t.unstable_runWithPriority (https://captainfact.io/vendor.1162576fecf1045ff8b8.js:2:1230074)
    at $o (https://captainfact.io/vendor.1162576fecf1045ff8b8.js:2:1155003)
```

**Comment by Betree** [comment]
Thanks for reporting this issue @ghostwan! 

It will be fixed by https://github.com/CaptainFact/captain-fact-frontend/pull/708 + https://github.com/CaptainFact/captain-fact-api/pull/283
