### ISSUE TITLE
Unexpected error when try to acces to notifications

### ISSUE THREAD

**Issue by marccharton** [CaptainFact/captain-fact#164]
# Describe the bug
Everytime I want to acces to my notifications, i get this page. 

![image](https://user-images.githubusercontent.com/3276889/101353786-75f15e80-3894-11eb-90e9-af399fe999b5.png)

# Device
- OS: Win32
- Browser: `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36`

# Context

**URL**: https://captainfact.io/u/narcomarch/activity

**Stacktrace**:
```
TypeError: Cannot read property 'username' of null
    at reply_to_comment (https://captainfact.io/app.66b23b017f1ad75f117a.js:1:124589)
    at Da (https://captainfact.io/app.66b23b017f1ad75f117a.js:1:127224)
    at ha (https://captainfact.io/vendor.1162576fecf1045ff8b8.js:2:1168889)
    at Tu (https://captainfact.io/vendor.1162576fecf1045ff8b8.js:2:1214154)
    at As (https://captainfact.io/vendor.1162576fecf1045ff8b8.js:2:1199699)
    at js (https://captainfact.io/vendor.1162576fecf1045ff8b8.js:2:1199624)
    at Es (https://captainfact.io/vendor.1162576fecf1045ff8b8.js:2:1196964)
    at https://captainfact.io/vendor.1162576fecf1045ff8b8.js:2:1155294
    at t.unstable_runWithPriority (https://captainfact.io/vendor.1162576fecf1045ff8b8.js:2:1230074)
    at $o (https://captainfact.io/vendor.1162576fecf1045ff8b8.js:2:1155003)
```

**Comment by Betree** [comment]
Thank your for opening this issue, it was reported in https://github.com/CaptainFact/captain-fact/issues/163 as well and fixed since
